### ISSUE TITLE
Style markdown in guideline overlay

### ISSUE THREAD

**Issue by fxstr** [infect-org/issues#29]
(Maybe we have to wait for the real guideline data – but here's the source: https://ssi.guidelines.ch, you're looking for «Empirische Therapie»)

**Comment by tobiaskneubuehler** [comment]
![Simulator Screen Shot - iPhone 11 Pro - 2019-10-02 at 13 33 03](https://user-images.githubusercontent.com/1210781/66041058-335a2680-e519-11e9-92dc-da3b00c28e18.png)

current styled:
- heading1
- heading2
- heading3
- listItem
- listUnorderedItemIcon
- codeInline
