### ISSUE TITLE
Frontend needs to be served from a web server

### ISSUE THREAD

**Issue by fxstr** [infect-org/issues#49]
We need some server side logic:
- robots.txt (hide beta)
- tenant config (features – needed to be known before we make the corresponding API calls)
- API endpoints (for dev environment)

**Comment by linaGirl** [comment]
@fxstr is this still the plan?

**Comment by fxstr** [comment]
IMO not. Converted the robots.txt-issue to a new one: https://github.com/infect-org/issues/issues/103
