### ISSUE TITLE
Pass showHidden flag to server

### ISSUE THREAD

**Issue by fxstr** [infect-org/issues#54]
See #47.

If 
- release channel is testing (app) or
- user adds `?preview` (web),
then
- add `?showAllData=true` to diagnosis and guideline endpoints.

**Comment by tobiaskneubuehler** [comment]
@fxstr same as https://github.com/infect-org/issues/issues/48 right?

**Comment by fxstr** [comment]
@tobiaskneubuehler True! Closing #48 as this issue contains the better description.
