### ISSUE TITLE
Clear all filter is only interactive in lower half

### ISSUE THREAD

**Issue by fxstr** [infect-org/issues#55]
![image](https://user-images.githubusercontent.com/1211144/66254091-e4f39480-e771-11e9-8a60-a823cf2c8ff7.png)

Cannot be clicked in upper half

**Comment by fxstr** [comment]
![image](https://user-images.githubusercontent.com/1211144/66399810-8d0e9500-e9e0-11e9-992a-778fc79479fc.png)

**Comment by fabianjordi** [comment]
…ich hab das verhalten teilweise auch, erkenne noch kein muster. und es betrifft nur den "clear all"-button, nicht die buttons links von diesem.

**Comment by fabianjordi** [comment]
fixed.

**Comment by fxstr** [comment]
@fabianjordi Do you recall the reason for the issue?

**Comment by fabianjordi** [comment]
@fxstr still don't know the reason, only added an overflow: hidden to the container and it seems to work…
