### ISSUE TITLE
Style new content in guideline drawer

### ISSUE THREAD

**Issue by fxstr** [infect-org/issues#61]
Is:
![image](https://user-images.githubusercontent.com/1211144/66387906-43fd1780-e9c5-11e9-9fc2-a8aeaaa62bf4.png)

Should be:
(TBD)

**Comment by fxstr** [comment]
Maybe:
![image](https://user-images.githubusercontent.com/1211144/66399394-d3afbf80-e9df-11e9-87fe-3d7e001181ca.png)

**Comment by fabianjordi** [comment]
ohne icons bei den untersten links.
