### ISSUE TITLE
Latest update is empty on most diagnoses

### ISSUE THREAD

**Issue by fxstr** [infect-org/issues#68]
E.g. missing on meningitis:
![image](https://user-images.githubusercontent.com/1211144/66912244-82708300-f012-11e9-9048-40456836111a.png)

Is there data missing (content issue) or does the API not correctly return the available data?

**Comment by pascalmfrey** [comment]
Dates (mostly of last check after first feedback from anresis) added.

Date format on frontend is MM/DD/YYYY -> change to DD/MM/YYYY?

**Comment by fxstr** [comment]
@pascalmfrey There's already an issue for updating the date format: https://github.com/infect-org/issues/issues/71. I'd go with `YYYY-MM-DD` to make the order clear … with the slashes, this is just not the case, sadly.

**Comment by pascalmfrey** [comment]
> I'd go with `YYYY-MM-DD` to make the order clear …

Excellent, sorry for double posting!
