### ISSUE TITLE
Add updated field to every therapy

### ISSUE THREAD

**Issue by fxstr** [infect-org/issues#73]

**Comment by fxstr** [comment]
@pascalmfrey Please make sure to use the direct link on the data source, e.g. https://ssi.guidelines.ch/guideline/2315/9042

**Comment by pascalmfrey** [comment]
I have now changed the links to consistently link to the guideline, e.g. "Meningitis" [https://ssi.guidelines.ch/guideline/2315](https://ssi.guidelines.ch/guideline/2315) instead of the "Empirical therapy" subsection, as there is also bits of information from other sections in the drawer.
