### ISSUE TITLE
Implement/provide feedback for inputs anresis

### ISSUE THREAD

**Issue by fxstr** [infect-org/issues#74]
[UnterschiedeINFECT_SSI.xlsx](https://github.com/infect-org/issues/files/3752007/UnterschiedeINFECT_SSI.xlsx)

**Comment by pascalmfrey** [comment]
Done except "Acute Bacterial Sinusitis". I don't understand the the difference, as he's citing the doses for children but then says there is no guideline for children in SSI. Any ideas? If not, lets drop it and close the issue.

**Comment by fxstr** [comment]
I cross checked your therapies for children and SSI's, they seem to be identical. Works for me.
