### ISSUE TITLE
Harmonize primary/alternative therapies

### ISSUE THREAD

**Issue by fxstr** [infect-org/issues#75]

**Comment by pascalmfrey** [comment]
Suggestion for definitions:

Primary therapy: any first-line therapy that is recommended given all special situations.

Alternatives: any therapy that may be given despite the absence of a hard contraindication for the primary therapy; e.g. patient preference, easier management, etc.

**Comment by pascalmfrey** [comment]
Let's put this into the same discussion as the definition of "empirical therapy".
