### ISSUE TITLE
Would it make sense to add diagnoses with potential empirical therapies?

### ISSUE THREAD

**Issue by fxstr** [infect-org/issues#86]
https://ssi.guidelines.ch/guideline/2272/8788, https://ssi.guidelines.ch/guideline/2273/8793 und https://ssi.guidelines.ch/guideline/2271 may contain empirical therapies (depending on the definition of an empirical therapy).

**Comment by pascalmfrey** [comment]
The SSI guideline itself calls e.g. the therapy for Syphillis ["specific"](https://ssi.guidelines.ch/guideline/2271/8780)
I do not really consider a therapy "empirical" when the causative organism is already known, but let's discuss this at our next meeting and include Silvio in the discussion. I think we need to define this properly.

**Comment by pascalmfrey** [comment]
This has now been resolved: any therapy that is recommended for a known pathogen is considered a specific therapy, while therapies for diagnoses with unknown pathogens are being considered empirical.
