### ISSUE TITLE
Add margin bottom to guidelines

### ISSUE THREAD

**Issue by fxstr** [infect-org/issues#87]
So that «Show resistance» button does not overlay content of guideline

**Comment by tobiaskneubuehler** [comment]
![Simulator Screen Shot - iPhone 11 Pro Max - 2019-10-30 at 12 43 05](https://user-images.githubusercontent.com/1210781/67855518-ddc26b00-fb12-11e9-8975-76c3bb81bea6.png)

@fxstr like this?

**Comment by tobiaskneubuehler** [comment]
![image](https://user-images.githubusercontent.com/1210781/67856311-84f3d200-fb14-11e9-9245-43dface8015c.png)

**Comment by fxstr** [comment]
Yesss!
