### ISSUE TITLE
Improve abbreviations of microorganisms

### ISSUE THREAD

**Issue by fxstr** [infect-org/issues#92]
Streptococci cannot be distinguished from one another. Options:

- Use «S. agalac», «S. bovis» etc. But this would lead to issues with «Achromobacter sp.» and «Acinetobacter sp.».
- Add new field to API/back office («Short name» on bacterium)

![Image from iOS](https://user-images.githubusercontent.com/1211144/68033170-7564bc80-fcbf-11e9-9135-3a7cb810596b.png)

**Comment by fxstr** [comment]
@pascalmfrey What would be a smart/good solution?

**Comment by fxstr** [comment]
If there were good short names, we should also use them on the web app to improve the usage of space.

**Comment by pascalmfrey** [comment]
What happened to the good short names we had? Sorry for missing this issue as I'm not using the app to access INFECT...
As many other people do use the app I see this as a very critical issue as it makes using the app pretty useless at the moment!
I still have a GSheet with the short names if it's gone missing.

**Comment by pascalmfrey** [comment]
The short names are also still in the old data master file (sheet "Bacterium", scroll to the right, after language names): 
https://docs.google.com/spreadsheets/d/1koB55f2_vcc4rq4E0J7b0Xxveooy5MpEyJ_Cyb_4rK4/edit#gid=261275403

**Comment by fxstr** [comment]
@linaGirl Was there a change on the API or did we just never use the short names? The current INFECT app (1.8.7) uses long names.

**Comment by pascalmfrey** [comment]
> The current INFECT app (1.8.7) uses long names.
I just noticed that as well, should be changed asap as the app can't really be used with this...

**Comment by fxstr** [comment]
Fixed with API update by @linaGirl
